name: Prod Deployment
on:
  push:
    branches:
      - main
jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lints
        run: npm run lint

      - name: Run tests
        run: npm run vitest

      - name: Run build
        run: npm run build

      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_URL }}
